### ISSUE TITLE
Create Word Doc to Review Sections

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#10]
Need to review text for each housing type

Definitions (short)
Definitions (long)
History
Layouts
Potential Layouts
#4 Boxes
#9 Deeper Context

**Comment by theryankelly** [comment]
Report History Text for Editing: https://mapc365.sharepoint.com/:w:/s/DataServicesSP/EUHkYHjMUDlEgooF6h3W_FcBpGLSesmPLCLG986MRb7irQ?e=yPqbN6

**Comment by alexislynn** [comment]
Text saved here:
\data-sync\Public\SG Land Use\SUB-REGIONS\SouthWest\Projects\LL Phase 2 - SWAP-TRIC\Digital toolkit\TEXT

**Comment by theryankelly** [comment]
Have word documents closing issue
