### ISSUE TITLE
Create Social Cards and Icon

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#12]
- [ ] Add meta tags for twitter card image

**Comment by alexislynn** [comment]
Text for the cards is saved the master text doc - within each of the housing types under the headers "cool things to know about [housing type]" "So why don't I see more in my town?" and "One Little Question" (I'm totally open to changing the headers if you have ideas)
\data-sync\Public\SG Land Use\SUB-REGIONS\SouthWest\Projects\LL Phase 2 - SWAP-TRIC\Digital toolkit\TEXT

**Comment by theryankelly** [comment]
Will use definition images in social card sharing. Main link will be hero image

**Comment by theryankelly** [comment]
Completed a version for Twitter and FB exist

![image](https://user-images.githubusercontent.com/2421382/149030985-c78aa9e0-f515-4d39-8970-728899b39eb5.png)
