### ISSUE TITLE
Video Content Section

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#58]
Guessing will be handled before upload to Youtube:
- [x] Thumbnails
- [x] Titles / names of housing types match site?
- [x] Font choice for video match site?

Needed for sharing the videos on the site:
- [x] Youtube links
- [x] Section titles
- [x] Descriptions

**Comment by theryankelly** [comment]
Example video two added to site for review:
![image](https://user-images.githubusercontent.com/2421382/143916443-a7a3bfc3-eb24-4144-bfb7-aa194e80ff0c.png)

**Comment by alexislynn** [comment]
Video 1: Why Living Little? 
There’s more to Greater Boston’s housing crisis than simply a lack of affordable housing. In the region’s suburbs, where most housing is single-family detached houses, there is also a lack of different types of housing, which leads to a mismatch between available housing options and the needs of the people who live here. 

Video 2: Barriers to Living Little
If so many people want smaller housing options, why does it seems like huge, expensive houses the only things being built in many suburban towns? This video explains breaks down housing costs and the ways that local policy can encourage certain types of housing. 

Video 3: Living Little in our Communities 
in most suburban neighborhoods, it’s no longer legal to build modest homes like duplexes or backyard cottages. But these rules can be changed!

Youtube links coming soon!

**Comment by alexislynn** [comment]
Youtube links for videos - 
1- Why Living Little? https://youtu.be/Zf6dtAg9pfs
2- Barriers to Living Little https://youtu.be/X1qwyLmjA9s
3- Living Little in our Communities https://youtu.be/XZ5rZV8aX2Q

**Comment by theryankelly** [comment]
Added and working
