### ISSUE TITLE
Intro Text

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#63]
- [x] Remove bold of font
- [x] Confirm copy
- [x] Move out of Hero

![image](https://user-images.githubusercontent.com/2421382/143069429-10869424-e13a-4844-854a-bb8d80677e00.png)

**Comment by theryankelly** [comment]
Should Read More and link to About be first action we give to visitors?

**Comment by theryankelly** [comment]
Current Intro Text: 
> The Greater Boston region is experiencing a housing crisis stemming from lack of affordable housing and appropriate housing types for current household incomes and formations. sMAPC’s Living Little project investigates small housing typologies for MAPC’s South West Advisory Planning Committee (SWAP) and Three Rivers Interlocal Council (TRIC) subregions. 
> Read more about Living Little.


Header Text from XD: 
> The Greater Boston region is experiencing a housing crisis stemming from lack of affordable housing and appropriate housing types for current household incomes and formations. MAPC’s Living Little project investigates small housing typologies for MAPC’s South West Advisory Planning Committee (SWAP) and Three Rivers Interlocal Council (TRIC) subregions.

@alexislynn do we need to keep reference the SWAP and TRIC subregions on the home page? Can we keep this mention to the about page?

Proposed Alterative:
> The Greater Boston region is experiencing a housing crisis stemming from lack of affordable housing and appropriate housing types for current household incomes and formations. MAPC’s Living Little project investigates small housing typologies that could serve as alternative housing types to meet the ever-growing demand for housing in the region.

**Comment by theryankelly** [comment]
Bold
![image](https://user-images.githubusercontent.com/2421382/143913564-da191e4e-71c3-4772-87d6-475a9b4466d0.png)

Not Bold
![image](https://user-images.githubusercontent.com/2421382/143913452-dba6762a-9332-4cc8-af34-4d3e9f622e62.png)

**Comment by alexislynn** [comment]
Intro text for below hero image - 
Living Little explores different types of small housing that would be well-suited for suburban communities throughout Greater Boston, where larger homes are more common. Smaller housing can provide options for a variety of smaller households—from millennials just starting out to baby boomers looking to downsize—helping towns meet need, retain household diversity, and take a “little” step towards addressing the region’s housing crisis. Read more about Living Little.
[last sentence links to "About Living Little" section]

**Comment by alexislynn** [comment]
@theryankelly you're right, any time there's a reference to SWAP or TRIC or SSC we can make it more generally about suburban Boston

**Comment by trust-kimberly** [comment]
Updated intro/hero text:

![Screen Shot 2021-12-20 at 10 51 33 AM](https://user-images.githubusercontent.com/62153141/146795144-e23a6375-95f3-44bf-a135-f81d31eb6a7c.png)
