### ISSUE TITLE
Housing type selction section: set section top at top of gray rather than selector

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#64]
Current: 
![image](https://user-images.githubusercontent.com/2421382/143069650-b6f58a19-f8e7-4c30-8415-07cea2af0af6.png)

Proposed:
![image](https://user-images.githubusercontent.com/2421382/143069707-2dc28444-ebcd-445c-9040-4d5b9b2afd8c.png)

**Comment by trust-kimberly** [comment]
Resolved and up on staging.

**Comment by theryankelly** [comment]
Updated with padding. Looks Good
