### ISSUE TITLE
Yellow Header Highlight

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#65]
The typology definitions section still has old yellow highlight styling. Should be consistent with the other sections

Old Version
![image](https://user-images.githubusercontent.com/2421382/143913813-734a18e6-da47-43dd-af9b-89eb91326719.png)

New Version
![image](https://user-images.githubusercontent.com/2421382/143913863-478ad28d-bdb9-4732-bad6-740853b7d4cb.png)

**Comment by trust-kimberly** [comment]
![Screen Shot 2021-11-29 at 3 38 23 PM](https://user-images.githubusercontent.com/62153141/143939589-e1f56319-58ad-4fd6-b126-4860198d4151.png)

Yellow highlight updated and pushed to staging.
