### ISSUE TITLE
Choose Housing Type Titles

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#67]
Will need to be consistent with typology titles. Which of the following do we want to go with? These are also listed in the Airtable.

- [ ] Townhouse   OR  Town Houses
- [ ] Mixed-use development OR Mixed Use
- [ ] Adjacent dwelling units OR Accessory Dwelling Unit
(ever use ADU?
- [ ] Cottage Developments OR Cottage Housing

I think the others are set, but I want to confirm:

- [ ] Tiny Houses
- [ ] Cohousing
- [ ] Single Family Retrofit

**Comment by theryankelly** [comment]
Airtable update with final choices

- Tiny Houses
- Townhouse
- Small-Scale Mixed-use Development
- Accessory Dwelling Units
- Cottage Housing
- Cohousing
- Single Family Home Conversion

**Comment by alexislynn** [comment]
Let's say Townhouses (plural) for consistency. Made the change in airtable
