### ISSUE TITLE
Cool Things to Know Cards

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#68]
The blue cards in the select a typography section are to be populated with the Cool Things to Know bullets.

This copy:
![image](https://user-images.githubusercontent.com/2421382/143920859-39090862-83cb-45b6-9a82-bc72c2407509.png)

Should live in these boxes.
![image](https://user-images.githubusercontent.com/2421382/143920765-6fd26f53-7dee-485b-aebc-4a7329a5592c.png)

**Comment by trust-kimberly** [comment]
Cool Things copy is now mapped to blue cards, however, a few things to note or consider: 
- I removed the yellow titles of the blue cards, given that our existing copy for Cool Things lack short titles.
- An odd number of cards wrap like so:
![Screen Shot 2021-11-29 at 2 51 00 PM](https://user-images.githubusercontent.com/62153141/143940085-578e94db-2053-4835-9bd4-e6f59b1770d5.png)
![Screen Shot 2021-11-29 at 2 51 23 PM](https://user-images.githubusercontent.com/62153141/143940086-c9f86791-fb73-4662-8291-0f975169c279.png)

- Some Cool Things are significantly longer than others in terms of text, causing awkward height differences:
![Screen Shot 2021-11-29 at 2 51 50 PM](https://user-images.githubusercontent.com/62153141/143940260-599e6399-5b35-4a3b-bd94-116ade837350.png)

One potential alternative?
![Screen Shot 2021-11-29 at 2 53 38 PM](https://user-images.githubusercontent.com/62153141/143940307-2c11ef20-7f53-43f5-a136-4dd85c310e22.png)

**Comment by trust-kimberly** [comment]
Currently on staging:
![Screen Shot 2021-12-20 at 1 32 01 PM](https://user-images.githubusercontent.com/62153141/146815714-8b4e894f-f9ad-44ef-9522-7283bd108535.png)

**Comment by alexislynn** [comment]
THanks Ryan! I made a few edits to the shortened cool things in airtable

**Comment by trust-kimberly** [comment]
Updated with shortened Cool Things copy. Think it works better visually while still concisely communicating pros of each type.

<img width="948" alt="Screen Shot 2021-12-22 at 10 37 39 AM" src="https://user-images.githubusercontent.com/62153141/147124887-b5e65e37-bdf2-46e4-a3cc-5c6f9ff3a002.png">

**Comment by theryankelly** [comment]
Updated and Resolved based on Airtable text.
