### ISSUE TITLE
"Pinterest" Grid of Housing Types Images Needed

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#7]
From 2.20.20 XD:
![Pinterest Gird](https://user-images.githubusercontent.com/2421382/78059618-26977d80-7358-11ea-90bd-04dbc92dee28.PNG)

- [x] **Tiny House** - Select a different image from the report where wheels aren't visible (don't want first image they see to be too closely associated with mobile homes)
- [x] **Cohousing** - Need different photo
- [x] **Mixed Use Development-** Need different photo 
- [x] **Row House** - needs new image that has some sort of yard (want folks who live in the suburbs to feel this will work for them)
- [x] **Accessory Dwelling** Unit not Adjacent Dwelling Unit (old version has as default text)
- [x] **Cottage Developments**-Need image credit and source

**Comment by alexislynn** [comment]
We've compiled a bunch of images (with permissions!) for each housing type. I'll go into the folder and will rename a few of the best ones (I'll put something like "use first" in the file name), and you can pick from those for whatever you think works in the pintrest board
\data-sync\Public\SG Land Use\SUB-REGIONS\SouthWest\Projects\LL Phase 2 - SWAP-TRIC\Digital toolkit\IMAGES

**Comment by theryankelly** [comment]
@alexislynn What are your thoughts on the images selected and the decision to go with tradition grid.

Current Site: 
![image](https://user-images.githubusercontent.com/2421382/143917172-5d0d05d4-34b2-42be-beee-e91c8ca84b34.png)

Matrix of images and housing types:
https://airtable.com/app04NjSVnA15ZAJN/tblDqmW60JZdDeGIc/viwL6QEfMjBOQ9muo?blocks=hide

**Comment by alexislynn** [comment]
I swapped out some of the images (in most cases because the original photo looked a little bit too urban and I want to really sell this as something that works in the suburbs). If any of the ones I picked don't work for whatever reason, let me know and I'll pick something else. thanks!

**Comment by alexislynn** [comment]
And traditional square grid looks great

**Comment by trust-kimberly** [comment]
Hey @alexislynn, I pulled the main definition images from the airtable. Hope this looks as expected!

![Screen Shot 2021-12-20 at 1 58 05 PM](https://user-images.githubusercontent.com/62153141/146818624-e4e06dcb-a481-4e57-b338-cda4e1aede4f.png)

**Comment by alexislynn** [comment]
Great, thanks! Are you using the same aspect ratio as the original photo? Some of these look squat (cottages and tiny house) while some seem to be stretched vertically (mixed use and townhouses)

**Comment by trust-kimberly** [comment]
Sorry about that! Adjusted styling to retain original aspect ratios:

![Screen Shot 2021-12-22 at 11 31 46 AM](https://user-images.githubusercontent.com/62153141/147125090-e7d4bf25-1918-47d7-a941-115dffb83164.png)

**Comment by theryankelly** [comment]
Finalized and live
