### ISSUE TITLE
Cohousing - A Few Small Questions

### ISSUE THREAD

**Issue by trust-kimberly** [MAPC/living-little-staging#78]
In [airtable](https://airtable.com/app04NjSVnA15ZAJN/tblDqmW60JZdDeGIc/viwL6QEfMjBOQ9muo?blocks=hide), we seem to have two answers but only one question for cohousing.

**Comment by theryankelly** [comment]
@alexislynn is reviewing an will update Airtable

**Comment by alexislynn** [comment]
Added questions in airtable
https://airtable.com/app04NjSVnA15ZAJN/tblDqmW60JZdDeGIc/viwL6QEfMjBOQ9muo?blocks=hide

**Comment by trust-kimberly** [comment]
Updated Cohousing questions and moved to review.

**Comment by theryankelly** [comment]
Closing Issue
