### ISSUE TITLE
Social Sharing content

### ISSUE THREAD

**Issue by trust-kimberly** [MAPC/living-little-staging#80]
Since each housing type deep dive section has a unique url, we can allow for sharing the links to socials along with predrafted copy.

Content needed:

- [x] Tweet copy, hashtags, etc.
- [x] Facebook copy

**Comment by theryankelly** [comment]
Closing as Twitter is pre-populated with definitions and link and Facebook with link (note facbeook is also pulling a site wide image for social card)
