### ISSUE TITLE
Export from both InDesign Typologies for Download

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#83]

**Comment by alexislynn** [comment]
Final plans and axons for the new housing types saved here:
\\data-sync\Public\SG Land Use\SUB-REGIONS\SouthWest\Projects\LL Phase 2 - SWAP-TRIC\Digital toolkit\IMAGES\SSC sketchup images
There's pdfs and an indesign file. I've been working in Citrix files so there may be issues with the linked images in the indesign file. If so, all the links are saved in the Assets folder

**Comment by theryankelly** [comment]
Exported and Added
