### ISSUE TITLE
Review A Few Small Questions sheet

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#85]
A Few Small Questions sheet: https://airtable.com/app04NjSVnA15ZAJN/tblK6DBm0wXoIc4Un/viwD13tLI0t9kWMbR?blocks=hide

**Comment by trust-kimberly** [comment]
Linked only the questions view:
![Screen Shot 2021-12-20 at 1 24 59 PM](https://user-images.githubusercontent.com/62153141/146814978-dc919113-2b45-4f33-a6f9-98bdb7599c91.png)

**Comment by theryankelly** [comment]
Looks good. Editable in Living Little Airtbale.

**Comment by alexislynn** [comment]
Reviewed with a few small tweaks, it looks good. FYI when I was reading through these I added a "type of concern" column in airtable to help organize my thinking - but I can delete if it will cause issues
