### ISSUE TITLE
Deeper Living Little Write Up for Link

### ISSUE THREAD

**Issue by theryankelly** [MAPC/living-little-staging#9]
Additional context info for entire region and why living little is an important

**Comment by alexislynn** [comment]
In the master text doc, towards the end under the heading "Context Page"
\data-sync\Public\SG Land Use\SUB-REGIONS\SouthWest\Projects\LL Phase 2 - SWAP-TRIC\Digital toolkit\TEXT

**Comment by theryankelly** [comment]
Closing Issue. Copy added to About page
